## Why PyTorch?

Super cool library with great research based applications - some of them are greatly optimized and runs C/C++ code under the hood.  

✅ **In short**: PyTorch is the framework of choice for researchers and practitioners who want rapid prototyping, strong community support, and smooth paths to production—while TensorFlow retains strengths in debugging, visualization, and some enterprise-scale workflows.
---

## PyTorch vs TensorFlow

| **PyTorch**                                   | **TensorFlow**                                                            |
| --------------------------------------------- | ------------------------------------------------------------------------- |
| Dynamic computation graphs (eager by default) | Static graphs by default (dynamic support improved via Keras integration) |
| Explicit CPU/GPU control                      | Simplified since TF 2.0 but less direct                                   |
| Pythonic, intuitive, faster to prototype      | Steeper learning curve                                                    |
| Strong documentation                          | Industry-leading documentation                                            |
| Uses external tools for visualization/logging | Built-in **TensorBoard**                                                  |
| Lightweight, easy experimentation             | Heavier deployment dependencies                                           |
| Debugging can be harder                       | Strong debugging tools                                                    |

---


# Scientific Computing with PyTorch

The **scientific computing power** of PyTorch is built on its **Tensor library** and rich ecosystem of tensor operations.

![tensor](https://thepracticaldev.s3.amazonaws.com/i/bp6ux6ppf5t5amwkxklq.jpg)

At its core, a **tensor** is an *n-dimensional array*—similar to a NumPy array but with additional deep learning and GPU acceleration capabilities.



---

# NumPy

![Numpy Ops](https://www.researchgate.net/publication/371375140/figure/fig2/AS:11431281194962536@1696298785617/Array-Slicing-in-NumPy-illustration-inspired-by.png)



* **NumPy** is the de facto library for scientific computing in Python, widely used for linear algebra, statistical operations, and nD arrays.
* **PyTorch Tensors** mirror NumPy’s API closely, making it easy for NumPy users to adopt PyTorch.
* Unlike NumPy, PyTorch tensors come with **native GPU support**, enabling large-scale computations to run orders of magnitude faster.
* PyTorch and NumPy are **highly interoperable**:

  * Convert a NumPy array → PyTorch tensor: `torch.from_numpy(ndarray)`
  * Convert a PyTorch tensor → NumPy array: `tensor.numpy()`

---

## Advantages of PyTorch Tensors

1. **GPU Acceleration**

   * Run tensor operations on CUDA-enabled GPUs with a simple `.to('cuda')` or `.cuda()` call.
   * Easily switch between CPU and GPU execution without code rewrites.

2. **Autograd Support**

   * PyTorch tensors integrate with the **autograd engine**, automatically tracking gradients for optimization.
   * This makes tensors not just numerical arrays but also core building blocks for training neural networks.

3. **Rich Mathematical Operations**

   * Built-in support for advanced linear algebra, convolution, Fourier transforms, and statistical functions.
   * Optimized under the hood with low-level libraries like **MKL**, **cuBLAS**, and **cuDNN**.

4. **Seamless Integration**

   * Interoperable with libraries like SciPy, Pandas, and scikit-learn.
   * Exportable to **ONNX** for use across other frameworks and runtimes.

---

## Quick Example

```python
import numpy as np
import torch

# NumPy array
np_array = np.array([[1, 2], [3, 4]])

# Convert to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)

# Move tensor to GPU
if torch.cuda.is_available():
    torch_tensor = torch_tensor.to('cuda')

print(torch_tensor)
```

✅ With just a few lines, the same scientific computing workflow can scale from CPU → GPU seamlessly.

---

👉 **In short:**

* **NumPy** = the gold standard for CPU-based scientific computing.
* **PyTorch tensors** = NumPy + GPU acceleration + automatic differentiation → making them the foundation for modern deep learning.

---



## PyTorch Philosophy

PyTorch was designed with a clear philosophy that prioritizes **developer experience**:

* **Stay out of the way** – Lightweight and minimal abstractions, so you focus on solving problems, not fighting the framework.
* **Cater to the impatient** – Quick to prototype, intuitive to learn, and fast to execute.
* **Promote linear code flow** – No hidden sessions or compilation steps; what you write is what runs.
* **Full Python interoperability** – Seamlessly integrates with the Python ecosystem (NumPy, SciPy, Pandas, scikit-learn, etc.).
* **As fast as anything else** – Competitive performance with other deep learning frameworks.

---

## Debugging in PyTorch

Because **PyTorch is a Python extension**, debugging is simple and familiar:

* Any **Python debugger** (e.g., `pdb`, `ipdb`, or IDE debuggers) works out of the box.
* Even the humble `print()` function works directly on tensors, autograd objects, and models.
* Errors are raised at runtime (thanks to dynamic graphs), making it much easier to trace issues back to source code.

This makes PyTorch particularly appealing for researchers and developers who iterate quickly and need **transparent debugging**.

---

## Why PyTorch Got So Popular

To train deep neural networks, frameworks rely on **computational graphs**—structures that represent operations and their derivatives for backpropagation.

![cgs](https://pytorch.org/assets/images/augmented_computational_graph.png)

Traditionally, frameworks like TensorFlow used **static computation graphs** (define-then-run). These graphs are fixed before execution, which allows optimizations but makes experimentation cumbersome.

PyTorch introduced **Dynamic Computation Graphs** (define-by-run):

* Graphs are built **on the fly** as operations occur.
* Debugging is intuitive, since errors appear exactly where they happen.
* Flexible for advanced models, research experiments, and quick iteration.

---

## PyTorch vs TensorFlow: The Modern Debate

Over the years, the gap between PyTorch and TensorFlow has narrowed (especially after TensorFlow 2.0 introduced eager execution). Yet, PyTorch remains the framework of choice for many researchers and developers due to several advantages:

1. **Ease of Learning & Use**

   * Pythonic syntax, intuitive APIs, and define-by-run graphs make PyTorch friendly for beginners and researchers alike.

2. **Research Flexibility**

   * Dynamic graphs let you modify architectures on the fly, perfect for prototyping and experimental work.

3. **Deep Python Integration**

   * Designed from the ground up to blend with Python tools and workflows, making it feel “native” in scientific computing pipelines.

4. **Community & Ecosystem**

   * Hugely popular in academia and research. The community contributes rich tutorials, papers, and open-source libraries across CV, NLP, RL, and more.

5. **Dynamic vs Static Graphs**

   * While TensorFlow supports dynamic graphs now, PyTorch was inherently designed for them—so its implementation is often smoother and more intuitive.

6. **Model Deployment**

   * TensorFlow still leads in enterprise deployment (TensorFlow Serving, TF Lite).
   * But PyTorch has **TorchScript**, **TorchServe**, and **PyTorch Mobile**, significantly closing the gap.

---

👉 **In short:**
PyTorch rose to dominance because it **put researchers first**—prioritizing flexibility, ease of use, and Python integration. With deployment tools now mature, PyTorch today is not just for prototyping but also for **production at scale**.



In [ ]:
!pip install torch #its preinstalled on Colab

In [ ]:
!ls

sample_data


In [ ]:
import numpy as np

V0 = np.array(1.3)
V1 = np.array([1., 2., 3.])
V2 = np.array([[1., 2.], [4., 5.]])
print(f'{V0}, {V1}, {V2}')

1.3, [1. 2. 3.], [[1. 2.]
 [4. 5.]]


In [ ]:
numpy_array = np.array([1, 2, 3])

In [ ]:
# Factory vs Constructor:
# Factory is technically a constructor, but more high level. It does the initialziing to safe values.
# Constructor is more manual. The user needs to initialize the things. Can be unsafe.
# Try to use factory if possible.

import torch

t1 = torch.Tensor(numpy_array)
# Constructor - same as torch.FloatTensor
# uses a default float32 tensor, this bechanvor can be changed
# all other tensors inherit from this main tensor class

t2 = torch.tensor(numpy_array)
# highly recommended to use!
# Factory Function
# call by value - creates a copy.
# does not share underlying memory with numpy!
# torch.tensor(data, dtype=None, device=None, requires_grad=False/True)


t3 = torch.as_tensor(numpy_array)
# recommended to use!
# Factory Function
# call by reference.
# CAN ACCEPT ANY PYTHON DATA S3TRUCTURE INCLUDING NUMPY ARRAYS
# always tries to avoid a copy of the data!
# we have to manually call requires_grad() function on the final tensor. It does not support requires_grad by default


t4 = torch.from_numpy(numpy_array)
# Factory Function
# produce a new tensor with the same data type
# share the underlying memory with numpy, changing one, will change another!
# CAN ACCEPT ONLY NUMPY ARRAYS

In [ ]:
numpy_array.dtype, t1.dtype, t2.dtype, t3.dtype, t4.dtype

(dtype('int64'), torch.float32, torch.int64, torch.int64, torch.int64)

In [ ]:
numpy_array *= 4

In [ ]:
numpy_array

array([ 4,  8, 12])

In [ ]:
t1, t2, t3, t4 #[n, n, y, y]

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [ ]:
t1 *= 2
numpy_array, t1, t2, t3, t4

(array([ 4,  8, 12]),
 tensor([2., 4., 6.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [ ]:
t2 *= 2
numpy_array, t1, t2, t3, t4

(array([ 4,  8, 12]),
 tensor([2., 4., 6.]),
 tensor([2, 4, 6]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [ ]:
t3 *= 2
numpy_array, t1, t2, t3, t4

(array([ 8, 16, 24]),
 tensor([2., 4., 6.]),
 tensor([2, 4, 6]),
 tensor([ 8, 16, 24]),
 tensor([ 8, 16, 24]))

In [ ]:
t4 *= 2
numpy_array, t1, t2, t3, t4

(array([16, 32, 48]),
 tensor([2., 4., 6.]),
 tensor([2, 4, 6]),
 tensor([16, 32, 48]),
 tensor([16, 32, 48]))

In [ ]:
t5 = t4.cuda()

t5.device, t4.device

(device(type='cuda', index=0), device(type='cpu'))

In [ ]:
t5 + t4 # Error because GPU + CPU won't work

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
print(t4.device, t3.device)
t6 = t4 + t3 # Works coz CPU+CPU
t6

cpu cpu


tensor([32, 64, 96])

In [ ]:
t6 = t4 + t5
t6

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
torch.eye(4, 4) # Returns an identity matrix

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(3, 4)

tensor([[0.9072, 0.8401, 0.7497, 0.2120],
        [0.3453, 0.1603, 0.8192, 0.6462],
        [0.2440, 0.4739, 0.8784, 0.8103]])

In [ ]:
data = torch.tensor([[1, 2, 3], [4, 5, 6]])
data[1, 0], data[0, 0:2], data[:2, :2]

(tensor(4),
 tensor([1, 2]),
 tensor([[1, 2],
         [4, 5]]))

#### Torch.tensor attributes

| Attribute | Data Type | Description |
|----|----|----|
|data|array_like | list, tuple, NumPy ndarray, scalar |
|dtype| torch.dtype | The tensor's data type|
|requires_grad | bool| Should autograd record operation |
|device | torch.device | Allocated on CPU or CUDA (GPU) |

torch.tensor(data, dtype=None, device=None, requires_grad=False) → Tensor


In [ ]:
data[1][0]

tensor(4)

In [ ]:
t = torch.tensor(data = [1, 2, 3], device='cuda', requires_grad=False)
t.device, t.dtype

(device(type='cuda', index=0), torch.int64)

In [ ]:
t = torch.tensor(data = [1, 2, 3], dtype=torch.float32, device='cpu', requires_grad=False)
t.device, t.dtype

(device(type='cpu'), torch.float32)

In [ ]:
t = torch.as_tensor(data = [1, 2, 3], dtype=torch.float32, device='cpu', requires_grad=False)
t

# Error coz as_tensor is not designed to take the requires_grad and device parameters.
# Because as_tensor does memory sharing and manipulating the grad and device in shared memory is not a good idea.
# The is just a safety feature for not including these parameters.

TypeError: as_tensor() got an unexpected keyword argument 'requires_grad'

In [ ]:
t = torch.as_tensor(data = [1, 2, 3], dtype=torch.float32, device='cpu')


In [ ]:
t.requires_grad_()

# This works as it is not doing the grad at the time of creating as done previously

tensor([1., 2., 3.], requires_grad=True)

# Autograd in PyTorch

One of PyTorch’s most powerful features is **Autograd**, its **automatic differentiation engine**.

###  Key Ideas

* **Automatic differentiation**: PyTorch tracks all tensor operations, so it can compute derivatives automatically.
* **Dynamic graph**: The backward graph is built *on the fly* from the forward pass. This makes debugging, experimentation, and model changes very easy.
* **Gradients**: Each tensor has an attribute `.grad` that stores the derivative of some scalar loss with respect to that tensor.
* **Chain rule**: PyTorch applies the chain rule under the hood for backpropagation.

---

## Example: A Simple Gradient Computation

```python
import torch

# Create a tensor with gradient tracking enabled
x = torch.tensor(2.0, requires_grad=True)

# Define a simple function: y = x^2 + 3x + 1
y = x**2 + 3*x + 1

# Backpropagate (compute dy/dx)
y.backward()

# Gradient is stored in x.grad
print(f"x: {x.item()}")
print(f"y: {y.item()}")
print(f"dy/dx: {x.grad.item()}")
```

### Output

```
x: 2.0
y: 11.0
dy/dx: 7.0
```

Explanation:

* $y = x^2 + 3x + 1$
* Derivative: $dy/dx = 2x + 3$
* At $x=2$, $dy/dx = 7$. PyTorch computed this automatically!

---

## Example: Working with Vectors

```python
# A vector of inputs
x = torch.randn(3, requires_grad=True)

# A simple function: y = sum(x^2)
y = (x**2).sum()

# Compute gradients
y.backward()

print("x:", x)
print("Gradient dy/dx:", x.grad)
```

Here, the gradient is simply $2x$, applied element-wise.

---

## Why Autograd Matters

* **Neural networks**: Training requires gradients of the loss w\.r.t. millions of parameters → Autograd handles this automatically.
* **Flexibility**: Works with dynamic graphs, so models can have loops, conditionals, or variable architectures.
* **Efficiency**: Optimized C++ backend with GPU acceleration.
* **Integration**: Works seamlessly with `torch.optim` for gradient-based optimization.

---

**In short**: With Autograd, you just define your forward computation in PyTorch. The backward pass and gradients are taken care of automatically, enabling easy and fast experimentation with new models.



In [ ]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad=True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad=True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad=True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad=True, dtype=torch.float16)

x1, x2, x3, x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [ ]:
z1 = x1 * x2
z2 = x3 * x4

print(f'z1 = {z1} and z2 = {z2}')
f = z1 + z2
print(f"f = {f}")

# f = x1 * x2 + x3 * x4
# f = 2 * 3 + 1 * 4
# df_dx1 = 3
# df_dx4 = 1

df_dx = grad(outputs = f, inputs = [x1, x2, x3, x4])
print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')



z1 = 6.0 and z2 = 4.0
f = 10.0
gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 4.0
gradient of x4 = 1.0


10 input image, 2 correct predictions, then loss = 8
10 input image, 4 correct predictions, then loss = 6
10 input image, 5 correct predicitons, then loss = 5

x1, x2, x3, x4 : 5, 6, 7, 8, then Loss = 5
x1 changes from 5 to 5.5 (somehow).. then loss = 4 (we want that).. but we are not going to change 5 to 5.5, but rather 5 + LR*(0.5).. LR most probably is going to be 0.001

0-100000

- iteration 1: Mutum 7... very very low
- i2: mutum 9999... very low
- i3: 99999.. very high
- i4: 50000.. closer
- i5: 55000.. very close
- i6: 55600.. very very close
- i7: 55650.. extremely close
- i8: 55651.. ext ext close

1000.. reduceLR_on_plateu


In [ ]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad=True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad=True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad=True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad=True, dtype=torch.float16)

f = x1 * x2 + x3 * x4

df_dx = grad(outputs = f, inputs = [x1, x2, x3, x4])
print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')



gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 4.0
gradient of x4 = 1.0


In [ ]:
import torch.nn.functional as F
import torch.optim as optim

opt = optim.SGD(params = [x1, x2, x3, x4], lr=0.001)
opt.zero_grad()

In [ ]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad=True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad=True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad=True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad=True, dtype=torch.float16)

z1 = x1 * x2
z2 = x3 * x4

f = z1 + z2

f.backward()

print(f'gradient of x1 = {x1.grad}')
print(f'gradient of x2 = {x2.grad}')
print(f'gradient of x3 = {x3.grad}')
print(f'gradient of x4 = {x4.grad}')



# Tensor Operation Types in PyTorch

PyTorch tensors support a wide range of operations. These can be grouped into four broad categories:

---

## 1. Reshaping Operations

Reshaping operations change the **structure** of a tensor without altering the underlying data.

* **`view()` / `reshape()`** – Change shape
* **`unsqueeze()` / `squeeze()`** – Add or remove dimensions of size 1
* **`transpose()` / `permute()`** – Reorder dimensions
* **`contiguous()`** – Ensure memory continuity for reshaping

```python
import torch

x = torch.arange(6)              # [0, 1, 2, 3, 4, 5]
x = x.view(2, 3)                 # Reshape to 2x3
print(x)

y = x.transpose(0, 1)            # Transpose (swap axes)
print(y)

z = x.unsqueeze(0)               # Add a new dimension at front
print(z.shape)  # torch.Size([1, 2, 3])
```

✅ **Use case:** Preparing tensors for batch processing, matrix multiplication, or feeding into neural network layers.

---

## 2. Element-wise Operations

These apply functions **independently** to each element of the tensor.

* Arithmetic: `+`, `-`, `*`, `/`, `**`
* Comparison: `<`, `>`, `==`
* Mathematical: `torch.exp`, `torch.log`, `torch.sin`, etc.

```python
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([3.0, 2.0, 1.0])

print(a + b)       # [4., 4., 4.]
print(a * b)       # [3., 4., 3.]
print(torch.exp(a))  # element-wise exponential
```

✅ **Use case:** Activation functions, normalization, element-wise arithmetic in model layers.

---

## 3. Reduction Operations

Reduction operations **aggregate tensor values** along one or more dimensions.

* **`sum()`** – Add elements
* **`mean()`** – Average values
* **`max()` / `min()`** – Get extreme values
* **`argmax()` / `argmin()`** – Index of max/min values
* **`prod()`** – Product of elements

```python
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

print(x.sum())             # 21
print(x.mean(dim=0))       # [2.5, 3.5, 4.5]
print(x.max(dim=1))        # values: [3., 6.], indices: [2, 2]
```

✅ **Use case:** Loss functions, pooling in CNNs, summarizing predictions.

---

## 4. Access Operations

Access operations let you **retrieve or modify** specific elements or slices of a tensor.

* **Indexing** (like Python lists): `x[0]`, `x[1, 2]`
* **Slicing**: `x[:, 1:3]`
* **Boolean indexing**: `x[x > 3]`
* **Advanced indexing**: Gather elements by index tensors

```python
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(x[0, 1])        # 20
print(x[:, 2])        # [30, 60]
print(x[x > 30])      # [40, 50, 60]
```

✅ **Use case:** Extracting minibatches, masking inputs, or modifying tensor values during preprocessing.

---

# 🔑 Summary

* **Reshaping** → Change structure/dimensions (e.g., `.view()`, `.transpose()`)
* **Element-wise** → Operate on each element individually (e.g., `+`, `exp`)
* **Reduction** → Aggregate across dimensions (e.g., `sum`, `mean`, `max`)
* **Access** → Retrieve, slice, or mask values (e.g., indexing, boolean masks)



In [ ]:
import torch

t = torch.tensor([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
    [2, 2, 2, 2]
], dtype=torch.float32)

In [ ]:
t.shape, t.size(), len(t.shape)

(torch.Size([3, 4]), torch.Size([3, 4]), 2)

In [ ]:
torch.tensor(t.shape).prod()

tensor(12)

In [ ]:
t.numel()

12

### Why knowing these is important?

When we reshape a tensor, the reshaping operation must account for all of numel (or total number of elements). We if we have 12 elements, we can only build 1x12, 12x1, 6x2, 2x6, 3x4, 4x3 reshaped tensors

In [ ]:
t.reshape(1, 12)

tensor([[0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.]])

In [ ]:
t.reshape(2, 6)

tensor([[0., 0., 0., 0., 1., 2.],
        [3., 4., 2., 2., 2., 2.]])

In [ ]:
t.reshape(6, -1)

tensor([[0., 0.],
        [0., 0.],
        [1., 2.],
        [3., 4.],
        [2., 2.],
        [2., 2.]])

In [ ]:
t.reshape(4, 3)

tensor([[0., 0., 0.],
        [0., 1., 2.],
        [3., 4., 2.],
        [2., 2., 2.]])

In [ ]:
t.reshape(2, 2, 3)

tensor([[[0., 0., 0.],
         [0., 1., 2.]],

        [[3., 4., 2.],
         [2., 2., 2.]]])

In [ ]:
print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.]])
torch.Size([1, 12])


**Squeezing a Tensor**

Removes all the dimensions that have a length of 1

**Unsqueezing a Tensor**
Adds a dimension that has a length of 1.

In [ ]:
print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.]])
torch.Size([1, 12])


In [ ]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.])
torch.Size([12])


In [ ]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim = 0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim = 0).shape)

tensor([[0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.]])
torch.Size([1, 12])


**Use cases?**

Neural networks are always trained in a batch of samples. This is troubling because when we want to test 1 image, we do not have an array, we only have 1 image. Well we unsqueeze it to fake a batch.

We use this function that is very common, called Flatten. This essentially create a new tensor that is only 1D. This is done to connect our data to next Fully Connected Layers. We use squeeze function for this.

Let's implement such a function.

In [ ]:
t

tensor([[0., 0., 0., 0.],
        [1., 2., 3., 4.],
        [2., 2., 2., 2.]])

In [ ]:
def flatter(t):
  t = t.reshape(1, -1)
  t = t.squeeze()
  return t

t.shape, t


(torch.Size([3, 4]),
 tensor([[0., 0., 0., 0.],
         [1., 2., 3., 4.],
         [2., 2., 2., 2.]]))

In [ ]:
flatter(t)

tensor([0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.])

In [ ]:
import torch

t1 = torch.tensor([
    [1, 2],
    [3, 4]
])

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.cat((t1, t2), dim=0)

# Vertical stacking --> dim = 0.
# Horizonatal stacking --> dim = 1.

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

![ops](https://ucarecdn.com/9f29f62d-5e96-430a-be4b-22f007983072/)

In [ ]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
t.reshape(2, -1)

tensor([[0., 0., 0., 0., 1., 2.],
        [3., 4., 2., 2., 2., 2.]])

In [ ]:
img1 = torch.tensor([
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1]
])

img2 = torch.tensor([
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2]
])

img3 = torch.tensor([
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3]
])

In [ ]:
batch = torch.stack((img1, img2, img3))
batch.shape, batch

(torch.Size([3, 4, 4]),
 tensor([[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]],
 
         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],
 
         [[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]))

In [ ]:
## Explanation of each dimension:
## 3 → batch size (3 images)
## 1 → number of channels (grayscale image)
## 4 → height
## 4 → width

batch = batch.reshape(3, 1, 4, 4)
batch

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [ ]:
# let's get our first image

batch[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [ ]:
# let's get the first channel of our first image

batch[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
# let's get the first row of our first channel of our first image

batch[0][0][0]

tensor([1, 1, 1, 1])

In [ ]:
# let's get the first pixel of the first row of our first channel of our first image

batch[0][0][0][0]

tensor(1)

In [ ]:
# Let's see how we flatten our image inside the batch

batch.reshape(1, -1)[0]


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
batch.reshape(1, 4, -1)[0]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
batch.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
batch.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [5, 6],
    [7, 8]
], dtype=torch.float32)

In [ ]:
t1 + t2

tensor([[ 6.,  8.],
        [10., 12.]])

In [ ]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [ ]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [ ]:
print(t1.add(2))

print(t1.sub(2))

print(t1.mul(2))

print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [ ]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [ ]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [ ]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [ ]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [ ]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [ ]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [ ]:
t.sum()

tensor(33.)

In [ ]:
t.prod()

tensor(0.)

In [ ]:
t.mean()

tensor(3.6667)

In [ ]:
t.std()

tensor(3.5707)

In [ ]:
t = torch.tensor([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3],
  [4, 4, 4, 4]
])

In [ ]:
t.sum(dim=0) # Vertical

tensor([10, 10, 10, 10])

In [ ]:
t.sum(dim=1) # Horizontal

tensor([ 4,  8, 12, 16])

In [ ]:
t.argmax(), t.max()

(tensor(12), tensor(4))

In [ ]:
t = torch.tensor([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3],
  [4, 4, 5, 4]
])
t.argmax(), t.max()

(tensor(14), tensor(5))

In [ ]:
t.argmin(), t.min()

(tensor(0), tensor(1))

In [ ]:
t.flatten()

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 4])

# What is `contiguous()`?

* A **tensor is contiguous** if its memory layout is stored sequentially (row-major order by default).
* Some operations (e.g., `transpose`, `permute`) only **change the view** of a tensor without actually rearranging memory.
* If you then try to call `.view()` on a non-contiguous tensor, PyTorch will complain.
* `.contiguous()` **forces a copy** of the tensor into contiguous memory.

---

## Example: Memory Layout Proof

```python
import torch

# Step 1: Create a 2x3 tensor
x = torch.arange(6).view(2, 3)
print("Original tensor:\n", x)

# Step 2: Transpose (non-contiguous!)
y = x.t()
print("\nTransposed tensor:\n", y)

# Check if contiguous
print("\nIs y contiguous?", y.is_contiguous())

# Step 3: Try to use view() on non-contiguous tensor
try:
    y.view(6)
except RuntimeError as e:
    print("\nError:", e)

# Step 4: Make it contiguous
z = y.contiguous()
print("\nContiguous tensor:\n", z)
print("Is z contiguous?", z.is_contiguous())

# Step 5: Show memory addresses
print("\nMemory addresses:")
print("y.storage():", y.storage())
print("z.storage():", z.storage())
```

---

### ✅ Sample Output

```
Original tensor:
 tensor([[0, 1, 2],
         [3, 4, 5]])

Transposed tensor:
 tensor([[0, 3],
         [1, 4],
         [2, 5]])

Is y contiguous? False

Error: view size is not compatible with input tensor's size and stride

Contiguous tensor:
 tensor([[0, 3],
         [1, 4],
         [2, 5]])
Is z contiguous? True

Memory addresses:
y.storage():  0 1 2 3 4 5   (non-linear stride mapping)
z.storage():  0 3 1 4 2 5   (copied into sequential memory)
```

---

## 📌 Why is it used?

1. **Reshaping with `.view()`**

   * `.view()` requires a tensor to be contiguous because it assumes linear memory.
   * `.contiguous()` fixes this by rearranging data in memory.

2. **Performance**

   * Some operations (like matrix multiplications) are optimized for contiguous memory.
   * Non-contiguous layouts can cause slower performance.

3. **Correctness**

   * After transpose/permute, data strides are different. `.contiguous()` ensures safe reshaping and consistent memory access.

---

## 🔑 Rule of Thumb

* Use `.contiguous()` **only when necessary** (e.g., before `.view()` or when operations explicitly require contiguous memory).
* Don’t call it unnecessarily, since it forces a memory copy.



In [ ]:
torch.arange(6).view(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
# Step 1: Create a 2x3 tensor
x = torch.arange(6).view(2, 3)
print("Original tensor:\n", x)

# Step 2: Transpose (non-contiguous!)
y = x.t()
print("\nTransposed tensor:\n", y)

# Check if contiguous
print("\nIs y contiguous?", y.is_contiguous())

# Step 3: Try to use view() on non-contiguous tensor
try:
    y.view(6)
except RuntimeError as e:
    print("\nError:", e)

# Step 4: Make it contiguous
z = y.contiguous()
print("\nContiguous tensor:\n", z)
print("Is z contiguous?", z.is_contiguous())

# Step 5: Show memory addresses
print("\nMemory addresses:")
print("x.storage():", x.storage())
print("y.storage():", y.storage())
print("z.storage():", z.storage())

Original tensor:
 tensor([[0, 1, 2],
        [3, 4, 5]])

Transposed tensor:
 tensor([[0, 3],
        [1, 4],
        [2, 5]])

Is y contiguous? False

Error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Contiguous tensor:
 tensor([[0, 3],
        [1, 4],
        [2, 5]])
Is z contiguous? True

Memory addresses:
x.storage():  0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
y.storage():  0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
z.storage():  0
 3
 1
 4
 2
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]




---


# PyTorch Main

# Working with the dataset

We will look at convolutional/image examples as they allow us to get a good intuition on axises and are more complex to work on just 1D data

### A common nn pipeline looks like this:
1. Prepare the data
2. Build the model
3. Train the model
4. Analyze the model

In [ ]:
import torch
import torchvision # provide access to datasets, models, transforms, utils, etc
import torchvision.transforms as transforms

In [ ]:
from torch.utils.data import Dataset

class Animals(Dataset):
  def __init__(self, csv_file):
    self.data = pd.read_csv(csv_file)

  def __getitem__(self, index):
    r = self.data.iloc[index]
    label, image = r
    return label, image

  def __len__(self):
    return len(self.data)

In [ ]:
# now let's work with FashionMnist

train_set = torchvision.datasets.FashionMNIST(
    root='./data'
    ,train=True
    ,download=True
    ,transform=transforms.Compose([
        transforms.ToTensor()
    ])
)



In [ ]:
for r in range(10):
  print(r)

0
1
2
3
4
5
6
7
8
9


In [ ]:
x = iter(range(10))
x, next(x), next(x)

(<range_iterator at 0x79f431459a40>, 0, 1)

In [ ]:
x = iter(range(10))
next(x), next(x), next(x), next(x), next(x), next(x), next(x), next(x), next(x), next(x)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [ ]:
train_set

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
           )

In [ ]:
next(iter(train_set))[1]

9

In [ ]:
next(iter(range(10)))

0

In [ ]:
i = 0

for j in train_set:
  print(j[1])
  i+= 1
  if i > 5:
    break

In [ ]:
train_loader = torch.utils.data.DataLoader(train_set
    ,batch_size=32
    ,shuffle=True
)

In [ ]:
iter(train_loader)

In [ ]:
next(iter(train_loader))[1]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

torch.set_printoptions(linewidth=120)

In [ ]:
len(train_set)

In [ ]:
train_set.train_labels

In [ ]:
train_set.train_labels.bincount() #frequency of each label, we have balanced class here

In [ ]:
sample = next(iter(train_set))

len(sample)

In [ ]:
image, label = sample

In [ ]:
plt.imshow(image.squeeze(), cmap='gray')
print('label:', label)

In [ ]:
batch = next(iter(train_loader))

len(batch), type(batch)

In [ ]:
images, labels = batch

In [ ]:
images.shape, labels.shape

In [ ]:
grid = torchvision.utils.make_grid(images, nrow=10)
plt.figure(figsize=(15,15))
plt.imshow(np.transpose(grid, (1,2,0)))
print('labels:', labels)

In [ ]:
import torch.nn as nn

class Network(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer = None

  def forward(self, t):
    t = self.layer(t)
    return t


# PyTorch Main (Let's start again)

# Working with the dataset

We will look at convolutional/image examples as they allow us to get a good intuition on axises and are more complex to work on just 1D data

### A common nn pipeline looks like this:
1. Prepare the data
2. Build the model
3. Train the model
4. Analyze the model

In [ ]:
import torch
import torchvision # provide access to datasets, models, transforms, utils, etc
import torchvision.transforms as transforms

In [ ]:
from torch.utils.data import Dataset

# Dataset is there to be able to interact with DataLoader

class MyDataset(Dataset):
  def __init__(self):
    self.data = (
        "This was an amazing product",
        "This was the shittiest product possible",
        "Amazing product, fast delivery",
        "Had to sell my kidney to buy this, and now my life has changed",
        "Good one!",
        "Bad One!"
    )

  def __getitem__(self, index):
    return self.data[index]

  def __len__(self):
    return len(self.data)

myData = MyDataset()

for m in myData:
  print(m)



In [ ]:
train_loader = torch.utils.data.DataLoader(myData, batch_size = 2, shuffle=True)

In [ ]:
for tr in train_loader:
  print(tr)

In [ ]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data',
    train=True,
    download=True,
    transform = transforms.Compose([
          transforms.ToTensor()
    ])
)

In [ ]:
for f in train_set:
  print(f)
  break

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

torch.set_printoptions(linewidth=120)

len(train_set)

In [ ]:
dir(train_set)

In [ ]:
train_set.train_labels.bincount()

In [ ]:
sample = next(iter(train_set))
sample

In [ ]:
image, label = sample
image.size()

In [ ]:
plt.imshow(image.squeeze(), cmap='gray')
print('label:', label)

In [ ]:
train_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size = 32,
    shuffle=True
)

In [ ]:
for tl in train_loader:
  print(len(tl[0]))
  print(tl[1])
  break

In [ ]:
batch = next(iter(train_loader))
batch

In [ ]:
images, labels = batch

images.shape, labels.shape

In [ ]:
grid = torchvision.utils.make_grid(images, nrow=10)
plt.figure(figsize=(15,15))
plt.imshow(np.transpose(grid, (1,2,0)))
print('labels:', labels)

In [ ]:
import torch.nn as nn

class Network(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer = None

  def forward(self, t):
    t = self.layer(t)
    return t

In [ ]:
class Network(nn.Module):
  def __init__(self):
    super().__init__()

# 9x9 convolved by 3x3> 7x7... 7x7 by 3x3.. 5x5
# 9x9 convolved by 5x5 > 5x5

    # input 28 # output 24 # receptive_field = 5
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    # input 24 # output 20 # receptive_field = 9
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
    # output > 20x20x12
    # input 12x20x20, output 120
    # input 10*512
    self.fc1 = nn.Linear(in_features=12*20*20, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=60)
    self.out = nn.Linear(in_features=60, out_features=10)

  def forward(self, t): # empty
    return t


In [ ]:
network = Network()

print(network)

In [ ]:
network.fc2

In [ ]:
dir(network.fc2)

In [ ]:
network.fc2.weight

In [ ]:
network.fc2.weight.shape

In [ ]:
class Network(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
    self.fc1 = nn.Linear(in_features=12*20*20, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=60)
    self.out = nn.Linear(in_features=60, out_features=10)

  def forward(self, t):
    # TODO implement this
    return t

network = Network()

for name, param in network.named_parameters():
  print(name, '\t\t', param.shape)

In [ ]:
import torch.nn.functional as F

In [ ]:

class Network(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

    self.fc1 = nn.Linear(in_features=12 * 4 * 4, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=60)
    self.out = nn.Linear(in_features=60, out_features=10) # 600 parameters of size 60x10. Input 60 inputs.

  def forward(self, t):
    # input layer
    x = t
    # conv1 layer
    x = self.conv1(x) # 1x28x28 > 6x24x24
    x = F.relu(x) # 6x24x24 > 6x24x24
    x = F.max_pool2d(x, kernel_size=2, stride=2) # 6x24x24 > 6x12x12
    # conv2 layer
    x = self.conv2(x) # 6x12x12 > 12x8x8
    x = F.relu(x) # no change
    x = F.max_pool2d(x, kernel_size=2, stride=2) #  12x8x8 > 12x4x4
    # reshapre
    x = x.reshape(-1, 12 * 4 * 4)
    # fc1 layer
    x = self.fc1(x) # 192 > 120
    x = F.relu(x)
    # fc2 layer
    x = self.fc2(x) # 120 > 10
    x = F.relu(x)
    # output layer
    x = self.out(x)
    # x = F.softmax(x, dim=1)
    return x

In [ ]:
torch.set_grad_enabled(False)

In [ ]:
sample = next(iter(train_set))
image, label = sample
image.shape, image.unsqueeze(0).shape


In [ ]:
network = Network()

In [ ]:
pred = network(image) # this is modern PyTorch

In [ ]:
pred = network(image.unsqueeze(0))  # this is old PyTorch

In [ ]:
pred, label # [0,0,0,0,0,0,0,0,0,1]

In [ ]:
pred, pred.shape, label

In [ ]:
pred.argmax(dim=1) # this time its 6 and 9

In [ ]:
F.softmax(pred, dim=1)

# SOFTMAX

In [ ]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Input values
x = torch.tensor([4., 3., 2., 1.])

# Apply softmax
softmax_vals = F.softmax(x, dim=0)

# Labels rounded for display
labels = [f"{val.item():.2f}" for val in x]

plt.figure(figsize=(8,5))

# Original values
plt.bar([i-0.2 for i in range(len(x))], x, width=0.4, label="Original values", alpha=0.7)

# Softmax probabilities
plt.bar([i+0.2 for i in range(len(x))], softmax_vals, width=0.4, label="Softmax probabilities", alpha=0.7)

# Fix x-axis ticks
plt.xticks(range(len(x)), labels)
plt.ylabel("Value / Probability")
plt.title("Softmax: Exponential Effect on Input Values")
plt.legend()
plt.show()


In [ ]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Input values
x = torch.tensor([0.4, 0.3, 0.2, 0.1])

# Apply softmax
softmax_vals = F.softmax(x, dim=0)

# Labels rounded for display
labels = [f"{val.item():.2f}" for val in x]

plt.figure(figsize=(8,5))

# Original values
plt.bar([i-0.2 for i in range(len(x))], x, width=0.4, label="Original values", alpha=0.7)

# Softmax probabilities
plt.bar([i+0.2 for i in range(len(x))], softmax_vals, width=0.4, label="Softmax probabilities", alpha=0.7)

# Fix x-axis ticks
plt.xticks(range(len(x)), labels)
plt.ylabel("Value / Probability")
plt.title("Softmax: Exponential Effect on Input Values")
plt.legend()
plt.show()


In [ ]:
F.softmax(pred, dim=1).sum()

In [ ]:
data_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size=10
)

In [ ]:
batch = next(iter(data_loader))
len(batch[0])

In [ ]:
images, labels = batch

preds = network(images)
preds.shape

In [ ]:
preds

In [ ]:
preds.argmax(dim=1)

In [ ]:
labels

In [ ]:
preds.argmax(dim=1).eq(labels)

In [ ]:
def get_num_correct(preds, labels):
  return preds.argmax(dim=1).eq(labels).sum().item()

In [ ]:
get_num_correct(preds, labels)

In [ ]:
import torch.optim as optim

torch.set_grad_enabled(True)

In [ ]:
preds = network(images)
loss = F.cross_entropy(preds, labels) # [0.1, 0.2, 0.4] - [0, 0, 1] | (0-0.1)**2 + (0-0.2)**2 + (1-0.4)**2 = LOSS????
loss.item()

In [ ]:
import math

# Natural logarithm (base e)
log_e = math.log(1/10)

print("ln(1/10):", log_e)


In [ ]:
print(network.conv1.weight.grad)

In [ ]:
loss.backward()

In [ ]:
print(network.conv1.weight.grad)

In [ ]:
kernel_3x3 = network.conv1.weight[1, 0].detach().cpu()
kernel_3x3

In [ ]:
kernel_3x3_grad = network.conv1.weight.grad[1, 0].detach().cpu()
kernel_3x3_grad

In [ ]:
print(network.conv1.weight.grad.shape)

In [ ]:
optimizer = optim.Adam(network.parameters(), lr = 0.01)

In [ ]:
optimizer.step()

In [ ]:
kernel_3x3 = network.conv1.weight[1, 0].detach().cpu()
kernel_3x3

In [ ]:
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.zero_grad()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.zero_grad()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.zero_grad()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.zero_grad()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
loss.backward()
optimizer.zero_grad()
optimizer.step()
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item(), get_num_correct(preds, labels)

In [ ]:
network = Network()

train_loader = torch.utils.data.DataLoader(train_set, batch_size=100)
optimizer = optim.Adam(network.parameters(), lr=0.001)

batch = next(iter(train_loader)) # Get Batch
images, labels = batch

preds = network(images) # Pass Batch
loss = F.cross_entropy(preds, labels) # Calculate Loss

loss.backward() # Calculate Gradients
optimizer.step() # Update Weights

print('loss1:', loss.item())
preds = network(images)
loss = F.cross_entropy(preds, labels)
print('loss2:', loss.item())

In [ ]:
torch.set_grad_enabled(False)
torch.set_grad_enabled(True)

In [ ]:
network = Network()

train_loader = torch.utils.data.DataLoader(train_set, batch_size=100, shuffle=True)
optimizer = optim.Adam(network.parameters(), lr=1e-3)  # 0.01 is high for Adam

network.train()

total_loss = 0.0          # will store SUM of per-example losses
total_correct = 0
total_examples = 0

for batch in train_loader:  # Get Batch
    images, labels = batch
    # labels should be class indices (LongTensor)
    if labels.dtype != torch.long:
        labels = labels.long()

    preds = network(images)                       # Pass Batch (logits)
    loss = F.cross_entropy(preds, labels)         # mean loss over this batch

    optimizer.zero_grad()
    loss.backward()                               # Calculate Gradients
    optimizer.step()                               # Update Weights

    bs = images.size(0)
    total_loss += loss.item() * bs                # accumulate per-example loss
    total_correct += get_num_correct(preds, labels)
    total_examples += bs

avg_loss = total_loss / total_examples
print(
    "epoch:", 0,
    "total_correct:", total_correct,
    "accuracy:", f"{total_correct/total_examples:.4%}",
    "loss:", f"{avg_loss:.4f}"
)


- loss.backward>> calculate gradients and store in weights(100)
- loss.backward>> add new gradients to old ones (200)
100
- optim.step>> updates the weights

In [ ]:
import torch
import torch.nn.functional as F
from torch import optim

# 1. Pick device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 2. Build and move model to device
network = Network().to(device)

# 3. Dataloader
train_loader = torch.utils.data.DataLoader(train_set, batch_size=100, shuffle=True)

# 4. Optimizer
optimizer = optim.Adam(network.parameters(), lr=1e-3)

# 5. Helper
def get_num_correct(logits, labels):
    preds = logits.argmax(dim=1)
    return (preds == labels).sum().item()

# 6. Training loop
for epoch in range(10):
    network.train()
    running_loss = 0.0
    running_correct = 0
    total_examples = 0

    for images, labels in train_loader:
        # move batch to GPU
        images, labels = images.to(device), labels.to(device)
        if labels.dtype != torch.long:
            labels = labels.long()

        optimizer.zero_grad()
        logits = network(images)
        loss = F.cross_entropy(logits, labels)

        loss.backward()
        optimizer.step()

        # stats
        batch_size = images.size(0)
        running_loss += loss.item() * batch_size
        running_correct += get_num_correct(logits, labels)
        total_examples += batch_size

    epoch_loss = running_loss / total_examples
    epoch_acc = running_correct / total_examples

    print(f"epoch {epoch:02d}  loss: {epoch_loss:.4f}  acc: {epoch_acc:.4%}")


In [ ]:
from google import genai

client = genai.Client(api_key="AIzaSyBUMiOTFthisWasRohansKeyWhichIsNotThereAgkW8IfpT33o")

response = client.models.generate_content(
    model="gemini-2.5-flash", contents="Explain why nearly everyone has moved out from Tensorflow to PyTorch?"
)
print(response.text)

While "nearly everyone has moved out from TensorFlow to PyTorch" might be an exaggeration, there's a strong and undeniable trend, especially in **academia, research, and new projects**, towards PyTorch. Many companies and existing large-scale deployments still heavily rely on TensorFlow.

However, the reasons for this significant shift are compelling and center around **developer experience, flexibility, and ease of use.**

Here's a breakdown of why PyTorch gained so much traction:

1.  **Dynamic Computation Graphs ("Define by Run")**
    *   **The Problem with TensorFlow 1.x:** TensorFlow 1.x used a **static computation graph** ("Define and Run"). You first had to build the entire graph of operations (like a blueprint) and *then* feed data into it to execute. This was great for optimization and deployment, but:
        *   **Debugging was a nightmare:** If something went wrong, you'd get cryptic errors often unrelated to the line of code that caused the issue, as the error came from the graph execution, not the graph definition.
        *   **Limited flexibility:** Control flow (if/else statements, loops) was difficult to implement dynamically within the graph. This made it challenging for models with variable structures (like RNNs with variable sequence lengths) or advanced techniques like reinforcement learning.
        *   **Less intuitive:** It felt less like writing regular Python code.
    *   **PyTorch's Solution:** PyTorch adopted a **dynamic computation graph** ("Define by Run"). Operations are executed immediately as they are defined, just like regular Python code.
        *   **Easy Debugging:** You can use standard Python debuggers (pdb, IDE debuggers) and inspect tensors at any point. Errors are precise and point to the exact line of code.
        *   **Pythonic Control Flow:** You can use native Python if/else statements and loops directly, making it incredibly flexible for complex models.
        *   **More Intuitive:** It feels much more like writing standard Python code, making it easier for new users to pick up.

2.  **Developer Experience and Pythonic API**
    *   **Less Boilerplate:** PyTorch generally requires less boilerplate code to define models and training loops.
    *   **NumPy-like Interface:** PyTorch's tensor operations are very similar to NumPy arrays, making it familiar and easy for Python data scientists to transition.
    *   **Simplicity:** The API is often perceived as cleaner and more straightforward.

3.  **Community and Ecosystem**
    *   **Research Adoption:** PyTorch quickly became the de-facto standard in academia and research due to its flexibility and ease of rapid prototyping. This led to a massive influx of research papers, open-source projects, and pre-trained models being released in PyTorch.
    *   **Active Community:** A vibrant and active community provides extensive support, tutorials, and shared resources.

4.  **Learning Curve**
    *   For many, especially those coming from a pure Python background, PyTorch has a significantly gentler learning curve compared to the complexities of TensorFlow 1.x's graph construction.

**TensorFlow 2.x's Response – Too Little, Too Late for Some?**

Google recognized these issues and completely overhauled TensorFlow with **TensorFlow 2.x**. Key changes included:
*   **Eager Execution (Dynamic Graphs) by default:** TF 2.x adopted dynamic graphs, essentially bringing the "Define by Run" paradigm that PyTorch popularized.
*   **Keras Integration:** Keras became the high-level API for TensorFlow, significantly simplifying model building.
*   **Cleaner API:** Efforts were made to simplify and unify the API.

While TF 2.x is a massive improvement and closed many of the gaps with PyTorch, the momentum had already shifted significantly. Many developers, researchers, and startups had already invested heavily in PyTorch, built their systems around it, and were comfortable with its established ecosystem. Changing frameworks, even to an improved version of the original, can be a non-trivial decision.

**Where TensorFlow Still Shines (and isn't "everyone" abandoning it):**

Despite the trend, TensorFlow remains incredibly powerful and is still widely used, especially in certain contexts:

*   **Production Deployment:** TensorFlow has a more mature and robust ecosystem for production deployment (e.g., TensorFlow Serving, TensorFlow Lite for mobile/edge devices, TensorFlow Extended (TFX) for full MLOps pipelines).
*   **Scalability (Historically):** TensorFlow was built from the ground up for Google's massive-scale distributed computing, and while PyTorch has caught up significantly, TF still benefits from that legacy for certain types of enterprise-scale deployments.
*   **TPU Support:** For companies leveraging Google's Tensor Processing Units (TPUs), TensorFlow often has tighter integration and optimization.
*   **Existing Investments:** Many large companies have significant legacy investments in TensorFlow 1.x or 2.x and established MLOps pipelines built around it. Migrating these systems is a massive undertaking.

In summary, the move towards PyTorch is driven by its superior **developer experience, flexibility, and ease of use, particularly in research and rapid prototyping.** While TensorFlow 2.x addressed many of these criticisms, PyTorch had already captured the hearts and minds of a large segment of the ML community.

In [ ]:
from google.genai import types
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Explain how AI works in a a lot of words",
    config=types.GenerateContentConfig(
        thinking_config=types.ThinkingConfig(thinking_budget=1) # Disables thinking
    ),
)
print(response.text)

Give me the list of top 20 countries, their GDP, population, capital names, major exports only in JSON form. DO NOT add any other text.

In [ ]:
from google import genai

response = client.models.generate_content(
    model="gemini-2.5-flash", contents="Give me the list of top 20 countries, their GDP, population, capital names, major exports only in JSON form. DO NOT add any other text. "
)
print(response.text)